export enum AdminRoute {
  Overview = '/admin',
  Clinics = '/admin/clinics',
  Affiliates = '/admin/affiliates',
  Facilities = '/admin/facilities',
  Patients = '/admin/patients',
  Transportation = '/admin/transportation',
  Shipping = '/admin/shipping',
  PickList = '/admin/pick-list',
  Inventory = '/admin/inventory',
  CaneInventory = '/admin/inventory/canes',
  Notifications = '/admin/notifications',
  Documents = '/admin/documents',
  Billing = '/admin/billing',
  PricingPlans = '/admin/pricing-plans',
  TransferIn = '/admin/transfer-in',
  TransferOut = '/admin/transfer-out',
  Terminations = '/admin/terminations',
}
